V-2.46.24 - adjust linewidth for UHD-screens - new remote-control-code clear  (start new model - do not save active model) - new remote-control-code system (do operating-system command, wait) - new code DUMP (MAN and remote-control, dump objects, listt ..) - new dev-tool TSTF (Demo_tstf_1 - do commands from file and rebuild plugin dynamic) - minor bugfixes

diff --git a/src/APP/do b/src/APP/do
--- a/src/APP/do
+++ b/src/APP/do
@@ -112,6 +112,12 @@ if [ $? -ne 0 ]; then
   echo "****** ERROR build gui-gtk3 *******"
   exit 1
 fi
+# rebuild executables GUI_*
+./do guiexe
+if [ $? -ne 0 ]; then
+  echo "****** ERROR build executables GUI_* *******"
+  exit 1
+fi
 # create core
 ./do c
 if [ $? -ne 0 ]; then
@@ -130,6 +136,13 @@ if [ $? -ne 0 ]; then
   echo "****** ERROR build demo-plugins *******"
   exit 1
 fi
+# rebuild processes
+./do processes
+if [ $? -ne 0 ]; then
+  echo "****** ERROR build processes *******"
+  exit 1
+fi
+#
 echo "- success do complete"
 exit 0
 fi
@@ -353,7 +366,7 @@ fi
 
 # build gcad3d-NC-processes
 if test "$1" = "processes"; then
-  make -f gcad3d.mak processes   ????
+  make -f gcad3d.mak processes
   exit $?
 fi
 
